service: projects-list-backend-sql

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: dev

functions:
  post:
    handler: handler.main
    events:
      - http: POST /

